name: Build, Analyze, Test

on:
  push:
    branches:
      - "main-**"
      - "dev-**"
      - "dev"
  pull_request:
    branches:
        - "main"
        - "dev"
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  scheme: ${{ 'default' }}

jobs:
  build:
    name: Build
    runs-on: test-runner
  
    steps:    
      - name: Clear Working Directory
        run: |
          rm -rf *
          rm -rf /Users/$(whoami)/github-actions/derived-data/${{ github.repository }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Destinations
        run: |
          result=$(./.github/workflows/id_devices.sh)
          if test ${#result} -eq 0; then
            echo "::error::No device destinations"
            exit 1
          fi
          echo Destination String: $result
      
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          xcodebuild clean build-for-testing \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          -sdk iphoneos \
          -destination generic/platform=iOS \
          -derivedDataPath /Users/$(whoami)/github-actions/derived-data/${{ github.repository }} \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration | xcpretty && exit ${PIPESTATUS[0]}

  analyze:
    name: Analyze
    runs-on: build-runner
    needs: [build, test]

    steps:

      - name: Clear Working Directory
        run: |
          rm -rf *
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Analyze
        run: |
          echo ${{ env.scheme }}
          scheme=${{ env.scheme }}
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          xcodebuild analyze \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          -sdk iphoneos \
          -derivedDataPath /Users/$(whoami)/github-actions/derived-data/${{ github.repository }} \
          -destination generic/platform=iOS | xcpretty && exit ${PIPESTATUS[0]}

  test:
    name: Test
    runs-on: test-runner
    needs: [build]

    steps:

      - name: Set Destinations
        run: |
          result=$(./.github/workflows/id_devices.sh)
          if test ${#result} -eq 0; then
            echo "::error::No device destinations"
            exit 1
          fi
          echo Destination String: $result
          echo "result=$result" >> $GITHUB_ENV

      - name: Test
        run: |
          echo Destination String: ${{ env.result }}
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          xcodebuild test-without-building \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          ${{ env.result }} \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          -derivedDataPath /Users/$(whoami)/github-actions/derived-data/${{ github.repository }} \
          -resultBundlePath /Users/$(whoami)/github-actions/derived-data/${{ github.repository }}/TestResults/TestResults.xcresult | xcpretty && exit ${PIPESTATUS[0]}

  result:
    name: Generate Test Results
    runs-on: test-runner
    needs: [test]

    steps:
      - name: Set path
        run: |
          path_to_file="/Users/$(whoami)/github-actions/derived-data/${{ github.repository }}/TestReults/TestResults.xcresult"
          echo "path=$path_to_file" >> $GITHUB_ENV

      - name: Generate Test Results
        uses: JohNan/xcresulttool@johnan/add-job-summary
        #uses: kishikawakatsumi/xcresulttool@v1.5.0
        with:
          path: ${{ env.path }}
          show-code-coverage: true
          title: Test Results Report
          create-check: false
          create-job-summary: true
        if: success() || failure()