name: Build, Analyze, Test

on:
  push:
    branches:
      - "main-**"
      - "dev-**"
      - "dev"
  pull_request:
    branches:
        - "main"
        - "dev"
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  scheme: ${{ 'default' }}

jobs:
  build:
    name: Build
    runs-on: build-runner
  
    steps:
      - name: Clear Working Directory
        run: |
          pwd
          ls
          rm -rf *
          pwd
          ls
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          xcrun xcodebuild clean build-for-testing \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          -sdk iphoneos \
          -destination generic/platform=iOS \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration | xcpretty && exit ${PIPESTATUS[0]}

  analyze:
    name: Analyze
    runs-on: build-runner
    needs: [build]

    steps:
      - name: Analyze
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          xcrun xcodebuild analyze \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          -sdk iphoneos \
          -destination generic/platform=iOS | xcpretty && exit ${PIPESTATUS[0]}

  test:
    name: Test
    runs-on: test-runner
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Destinations
        run: |
          result=$(./.github/workflows/id_devices.sh)
          echo Destination String: $result
          echo "result=$result" >> $GITHUB_ENV

      - name: Test
        run: |
          echo Destination String: ${{ env.result }}
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          echo "xcrun xcodebuild test-without-building \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          ${{ env.result}} \
          -derivedDataPath ./DerivedData \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          -resultBundlePath TestResults | xcpretty && exit ${PIPESTATUS[0]}"

          xcrun xcodebuild test-without-building \
          -scheme "$scheme" \
          -"$filetype_parameter" "$file_to_build" \
          ${{ env.result}} \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          -resultBundlePath TestResults | xcpretty && exit ${PIPESTATUS[0]}

      - name: Generate Test Results
        uses: kishikawakatsumi/xcresulttool@v1.5.0
        with:
          path: TestResults.xcresult
          show-code-coverage: false
          title: Test Results Report
        if: success() || failure()